# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Endpoint for authentication from the website

Resources:
    AuthFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: auth.default
            Runtime: nodejs16.x
            Timeout: 800
            MemorySize: 128
            CodeUri: ./dist/auth
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: auth-website
            AutoPublishAlias: live
            FunctionUrlConfig:
                AuthType: NONE

